USE sys;

DROP DATABASE IF EXISTS moviecollection;

DROP TABLE IF EXISTS Actor;
DROP TABLE IF EXISTS Movie;
DROP TABLE IF EXISTS Credit;
DROP TABLE IF EXISTS Genre;

CREATE DATABASE moviecollection;

Create TABLE Actor(
ActorId INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(50),
LastName VARCHAR(50)
);

CREATE TABLE Movie(
MovieId INT PRIMARY KEY AUTO_INCREMENT,
Title VARCHAR(75) NOT NULL,
ReleaseYear INT NOT NULL,
Rating VARCHAR(6)
);

CREATE TABLE Credit(
CreditId INT PRIMARY KEY AUTO_INCREMENT,
MovieId INT,
ActorId INT,
RoleName VARCHAR(25)
);

CREATE TABLE Genre(
GenreId INT PRIMARY KEY AUTO_INCREMENT,
GenreName VARCHAR(20)
);

ALTER TABLE Movie
ADD Director VARCHAR(50);